### PR TITLE
Add null shoulds

### PR DESCRIPTION
**Pull request by katafrakt**
This adds methods to match against being `null` and not being `null`.

### CODE REVIEW

**Comment by dmonagle** [comment]
This is a good idea. What happens if somebody calls this on a Nullable!x. I think that it should probably take this into consideration and have appropriate tests.

**Comment by katafrakt** [comment]
That's a good point. Last commit is what I came up with to support `Nullable` too.

**Comment by katafrakt** [comment]
any thoughts? :wink:

**Comment by dmonagle** [comment]
Looks good

**Pull request merged**
